### ISSUE TITLE
c_flat output is incorrect

### ISSUE THREAD

**Issue by keesj** [sehugg/bitmapfontgenerator#1]
When the c_flat output is selected in the bitmapfontgenerator the constructed array is missing a conlon between the generated characters.

![ss_k png](https://user-images.githubusercontent.com/57112/82927125-84bf9600-9f80-11ea-860d-5ec1d2c5c180.png)

Not sure how you want this fixed but I implemented the following

```
diff --git a/src/uifont.ts b/src/uifont.ts
index 8e551bc..da2ac88 100644
--- a/src/uifont.ts
+++ b/src/uifont.ts
@@ -310,6 +310,7 @@ function encodeFont() {
                 s += "0x" + hex(bytes[i]) + ((i<bytes.length-1)?",":"");
             }
             if (params.output=='c_nested') s += " },";
+            else if (params.output=='c_flat') s += ",";
             if (!c_output || params.newline) s += "\n";
         }
     }

```

**Comment by sehugg** [comment]
Thanks, fixed it!
